title: oracle-raspberrypi-weather-station
hero_image: images/banner.png
description: oracle-raspberrypi-weather-station description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-20"
steps:
  - title: Introduction
  - title: Registering your Weather Station
  - title: Assembling your Weather Station
  - title: Installing the software
  - title: Final hardware steps
  - title: Testing your Weather Station
  - title: Install the Weather Station outside
  - title: Wind sensors
  - title: Wifi
  - title: What next?
